services:
  db:
    container_name: db
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose: 
      - 5432
  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    ports: 
      - "8888:80"
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=danpgause@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  backend:
    container_name: backend
    env_file:
      - .env.config
    build:
      context: ./services/gpt-connection
    ports:
      - 8000:8000
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    expose: 
      - 3000


volumes:
  pgdata:
    external: true
  pgadmin-data:


