services:
  db:
    container_name: db
    env_file:
      - ./.env
    build: 
      context: ./services/postgres-db
      dockerfile: dockerfile-postgres-df.Dockerfile
    ports:
     - 5433:5432
    restart: always

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    external: true

